{
 "title": "Basalt Vultiserver",
 "tags": [
  "basalt",
  "vultiserver",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "### Target: `__TARGET_URL__`" } },
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({app=\"basalt-vultiserver\", service=\"healthcheck\", endpoint=\"ping\", level=\"info\"} [2m])"
    }
   ]
  },
  {
   "title": "Last Test Result",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time({app=\"basalt-vultiserver\", service=\"testrunner\", test=\"_summary\"} | json | unwrap failed [$__range])"
    }
   ]
  },
  {
   "title": "Last Run",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time({app=\"basalt-vultiserver\", service=\"testrunner\", test=\"_summary\"} | json | unwrap failed [$__range])"
    }
   ]
  },
  {
   "title": "Warnings (5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"basalt-vultiserver\", service!=\"healthcheck\", level=\"warning\"} [5m]))"
    }
   ]
  },
  {
   "title": "Recent Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{app=\"basalt-vultiserver\", service!=\"healthcheck\"}"
    }
   ]
  }
 ]
}